[package]
name = "hookedmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["fs", "io-util", "macros", "rt", "rt-multi-thread", "time", "sync", "parking_lot"] }
futures-util = "0.3.21"
hyper = { version = "0.14.17", features = ["http1", "server", "stream", "tcp"] }
mysql_async = "0.29.0"
chrono = "0.4.19"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
toml = "0.5.8"
once_cell = "1.9.0"
tracing = "0.1.30"
tracing-subscriber = { version = "0.3.8", features = ["env-filter"] }
rocketmap-entities = { git = "https://github.com/nappa85/rocketmap-entities.git" }
