[package]
name = "hookedmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
tokio = { version = "1.18.1", features = ["fs", "io-util", "macros", "rt", "rt-multi-thread", "time", "sync", "parking_lot"] }
futures-util = "0.3.21"
hyper = { version = "0.14.18", features = ["http1", "server", "stream", "tcp"] }
mysql_async = "0.29.0"
chrono = "0.4.19"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
toml = "0.5.9"
once_cell = "1.10.0"
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
rocketmap-entities = { git = "https://github.com/nappa85/rocketmap-entities.git" }
