[package]
name = "hookedmap"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt", "rt-multi-thread", "time", "sync", "parking_lot"] }
futures-util = "0.3"
hyper = { version = "0.14", features = ["http1", "server", "stream", "tcp"] }
mysql_async = "0.28"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.5"
once_cell = "1.8"
log = "0.4"
env_logger = "0.9"
rocketmap-entities = { git = "https://github.com/nappa85/rocketmap-entities.git" }
